import { MemeTemplate } from './types.ts';

export const POPULAR_TEMPLATES: MemeTemplate[] = [
  {
    id: 'drake',
    name: 'Drake Rejeita / Aprova',
    category: 'trending',
    url: 'https://api.memegen.link/images/drake.jpg',
    width: 600,
    height: 600,
    defaultTopText: 'Ler a documentação de 50 páginas',
    defaultBottomText: 'Descobrir tudo na base da tentativa e erro',
  },
  {
    id: 'db',
    name: 'Namorado Distraído',
    category: 'trending',
    url: 'https://api.memegen.link/images/db.jpg',
    width: 600,
    height: 400,
    defaultTopText: 'Novo framework que saiu ontem',
    defaultBottomText: 'Meu projeto inacabado há 6 meses',
  },
  {
    id: 'woman-cat',
    name: 'Mulher Gritando com o Gato',
    category: 'trending',
    url: 'https://api.memegen.link/images/woman-cat.jpg',
    width: 600,
    height: 400,
    defaultTopText: 'Você prometeu que ia dormir às 22h!',
    defaultBottomText: 'Eu lendo curiosidades sobre capivaras às 3h da manhã',
  },
  {
    id: 'fine',
    name: 'Tá Tudo Bem (Cachorro no Fogo)',
    category: 'work_tech',
    url: 'https://api.memegen.link/images/fine.jpg',
    width: 600,
    height: 337,
    defaultTopText: 'Deploy em produção na sexta-feira às 18h',
    defaultBottomText: 'Tá tudo bem.',
  },
  {
    id: 'rollsafe',
    name: 'Pense Bem (Roll Safe)',
    category: 'classic',
    url: 'https://api.memegen.link/images/rollsafe.jpg',
    width: 600,
    height: 338,
    defaultTopText: 'Os testes unitários não falham',
    defaultBottomText: 'Se você não escrever nenhum teste',
  },
  {
    id: 'cmm',
    name: 'Mude Minha Opinião (Change My Mind)',
    category: 'classic',
    url: 'https://api.memegen.link/images/cmm.jpg',
    width: 600,
    height: 400,
    defaultTopText: 'Modo escuro não é preferência',
    defaultBottomText: 'É questão de sobrevivência. Mude minha opinião.',
  },
  {
    id: 'gb',
    name: 'Cérebro Galáctico',
    category: 'classic',
    url: 'https://api.memegen.link/images/gb.jpg',
    width: 600,
    height: 700,
    defaultTopText: 'Resolver o bug com código limpo',
    defaultBottomText: 'Reiniciar o servidor até funcionar',
  },
  {
    id: 'disastergirl',
    name: 'Menina do Desastre',
    category: 'reactions',
    url: 'https://api.memegen.link/images/disastergirl.jpg',
    width: 600,
    height: 450,
    defaultTopText: 'Vendo o grupo da firma pegando fogo',
    defaultBottomText: 'Depois de subir a alteração e sair de férias',
  },
  {
    id: 'spiderman',
    name: 'Homens-Aranha Apontando',
    category: 'reactions',
    url: 'https://api.memegen.link/images/spiderman.jpg',
    width: 600,
    height: 338,
    defaultTopText: 'Frontend culpando o Backend',
    defaultBottomText: 'Backend culpando o Servidor',
  },
  {
    id: 'astronaut',
    name: 'Sempre Foi (Astronauta)',
    category: 'trending',
    url: 'https://api.memegen.link/images/astronaut.jpg',
    width: 600,
    height: 338,
    defaultTopText: 'Peraí, tudo isso era débito técnico?',
    defaultBottomText: 'Sempre foi.',
  },
  {
    id: 'bihw',
    name: 'Trabalho Honesto',
    category: 'work_tech',
    url: 'https://api.memegen.link/images/bihw.jpg',
    width: 600,
    height: 375,
    defaultTopText: 'Resolvendo 1 tarefa de 89 no Jira',
    defaultBottomText: 'Não é muito, mas é trabalho honesto',
  },
  {
    id: 'gru',
    name: 'Plano do Malvado Favorito (Gru)',
    category: 'classic',
    url: 'https://api.memegen.link/images/gru.jpg',
    width: 600,
    height: 600,
    defaultTopText: 'Abro 50 abas no Chrome pra estudar',
    defaultBottomText: 'O cooler do notebook parece uma turbina de avião',
  },
  {
    id: 'panik-kalm-panik',
    name: 'Pânico / Calma / Pânico',
    category: 'reactions',
    url: 'https://api.memegen.link/images/panik-kalm-panik.jpg',
    width: 600,
    height: 675,
    defaultTopText: 'O código compilou sem nenhum erro',
    defaultBottomText: 'O código compilou sem nenhum erro?!',
  },
  {
    id: 'doge',
    name: 'Doge',
    category: 'animals',
    url: 'https://api.memegen.link/images/doge.jpg',
    width: 600,
    height: 450,
    defaultTopText: 'muita inteligência',
    defaultBottomText: 'muito meme, tanta sabedoria, uau',
  },
  {
    id: 'grumpycat',
    name: 'Grumpy Cat (Gato Rabugento)',
    category: 'animals',
    url: 'https://api.memegen.link/images/grumpycat.jpg',
    width: 600,
    height: 450,
    defaultTopText: 'Pedi pra IA me deixar feliz',
    defaultBottomText: 'Ela respondeu: "Erro 404"',
  },
  {
    id: 'fry',
    name: 'Futurama Fry Desconfiado',
    category: 'reactions',
    url: 'https://api.memegen.link/images/fry.jpg',
    width: 600,
    height: 450,
    defaultTopText: 'Não sei se sou um gênio',
    defaultBottomText: 'Ou se só sei usar o Google muito bem',
  },
  {
    id: 'pigeon',
    name: 'Isso é um Pombo? (Anime)',
    category: 'classic',
    url: 'https://api.memegen.link/images/pigeon.jpg',
    width: 600,
    height: 338,
    defaultTopText: 'Olhando uma funcionalidade sem documentação',
    defaultBottomText: 'Isso é um bug ou uma feature?',
  },
  {
    id: 'wonka',
    name: 'Willy Wonka Irônico',
    category: 'classic',
    url: 'https://api.memegen.link/images/wonka.jpg',
    width: 600,
    height: 450,
    defaultTopText: 'Conte-me mais sobre sua startup bilionária',
    defaultBottomText: 'Parece extremamente inovador',
  },
  {
    id: 'bus',
    name: 'Dois Caras no Ônibus',
    category: 'trending',
    url: 'https://api.memegen.link/images/bus.jpg',
    width: 600,
    height: 338,
    defaultTopText: 'Lendo as notícias de hoje',
    defaultBottomText: 'Criando memes de gatinho',
  },
  {
    id: 'success',
    name: 'Menino do Sucesso (Success Kid)',
    category: 'reactions',
    url: 'https://api.memegen.link/images/success.jpg',
    width: 600,
    height: 450,
    defaultTopText: 'Mandei mensagem no grupo errado',
    defaultBottomText: 'Apaguei pra todos em 2 segundos',
  },
];
